FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# self-assessment

Self assessment APIs

## Self Employments Collection [/3000037190/2016-17/self-employments]

### List All Self Employments [GET]

+ Response 501 (application/json)

        {
          "code": "NOT_IMPLEMENTED",
          "message": "The resource is not implemented"
        }

### Create a Self Employment [POST]

You can create a self employment. 
Returns the HAL link to created self employment.

+ Request (application/json)

        {
            "name": "name",
            "commencementDate": "2016-05-25"
        }
    

+ Response 501 (application/json)

   + Body

            {
                "code": "NOT_IMPLEMENTED",
                "message": "The resource is not implemented"
            }